### ISSUE TITLE
EZID Service Data Form's Namespace field needs clarification

### ISSUE THREAD

**Issue by seth-shaw-unlv** [discoverygarden/dgi_actions#27]
For EZID, the "namespace" is simply the initial "ark:/99999/" which _may or may not_ be synonymous with a minting "shoulder". Simply adding the namespace will cause the minter to throw an error. E.g. using the test namespace ("ark:/99999/") to create a test ark this field should be "ark:/99999/fk4".

I recommend changing the label to "Shoulder" and providing the test minting shoulder in the description text as an example.

**Comment by jordandukart** [comment]
Resolved in https://github.com/discoverygarden/dgi_actions/pull/30.
