### ISSUE TITLE
ERC DataProfile doesn't serialize entity reference fields well

### ISSUE THREAD

**Issue by seth-shaw-unlv** [discoverygarden/dgi_actions#29]
I have an ERC DataProfile with a TypedRelation field type as the source for "Who". This results in sending "Who:65, relators:abr" (or the similar) to EZID.  I know the actual populating of "What", "When", and "Who" get set @ https://github.com/discoverygarden/dgi_actions/blob/v1.1.0/modules/dgi_actions_ezid/src/Plugin/DataProfile/Erc.php#L40, but I haven't traced back how the passed data array it is set and if we can account for it there or if it needs to be handled further upstream.

**Comment by jordandukart** [comment]
Resolved in https://github.com/discoverygarden/dgi_actions/pull/30.
