### ISSUE TITLE
EZID ARKs are not resolveable

### ISSUE THREAD

**Issue by seth-shaw-unlv** [discoverygarden/dgi_actions#31]
While the dgi_actions_ark_identifier submodule can _mint_ ARKS, [their `_status` value is currently set to `reserved`](https://github.com/discoverygarden/dgi_actions/blob/1.x/modules/dgi_actions_ark_identifier/src/Plugin/Action/MintArkIdentifier.php#L88) so that they can be deleted (as [noted in the README](https://github.com/discoverygarden/dgi_actions/blob/1.x/modules/dgi_actions_ark_identifier/README.md?plain=1#L33 )).

However, these ARKS, according to the EZID documentation, are not sent to the resolver, which means on the EZID page (E.g. https://ezid.cdlib.org/id/ark:/99999/fk46d7bs2v) the "Identifier as URL" for the identifier (e.g. https://n2t.net/ark:/99999/fk46d7bs2v) will return a 404 unless the repository manually sets the `_status` to `public`.

Also, I would think that the _expected_ behavior for the resulting persistent identifier link would be the resolver URL leading back to the object itself, not to the EZID object page.

**Comment by jordandukart** [comment]
Resolved in https://github.com/discoverygarden/dgi_actions/pull/32.
